/** Discover anime-category demo catalog (local covers; Talkie-shaped). */

export type DiscoverCategoryId =
  | "all"
  | "recommend"
  | "anime"
  | "school"
  | "romance"
  | "healing"
  | "fantasy"
  | "game";

export type DiscoverDemoCard = {
  id: string;
  /** Profile slug used for demo deep-links (aoi / mio). */
  hrefSlug: "aoi" | "mio";
  name: string;
  tagline: string;
  description: string;
  coverUrl: string;
  tags: string[];
  category: DiscoverCategoryId;
  chats: number;
  gender: "female" | "male" | "other";
};

export const DISCOVER_GENDERS = [
  { id: "all" },
  { id: "female" },
  { id: "male" },
  { id: "other" },
] as const;

export const DISCOVER_CATEGORIES = [
  { id: "recommend" },
  { id: "anime" },
  { id: "school" },
  { id: "romance" },
  { id: "healing" },
  { id: "fantasy" },
  { id: "game" },
] as const;

const COVER_PATHS = [
  "/discover/covers/72c44f9a-9ebd-4875-b323-89cd00d236a3.png",
  "/discover/covers/75392e40-6e5d-40d4-89e3-f375556ec9a4.png",
  "/discover/covers/7f76c1e8-10a2-44e9-9194-a6c86c520986.png",
  "/discover/covers/b15cdf0e-47f9-49df-8577-460c36ba3690.png",
  "/discover/covers/f11d929e-f820-4e88-b105-1aac15bbe0c7.png",
  "/discover/covers/fb8d0159-b384-4102-b429-a9c25bc49929.png",
  "/discover/covers/huaban-5281733834.png",
  "/discover/covers/huaban-5395167551.webp",
  "/discover/covers/huaban-5598647592.webp",
  "/discover/covers/huaban-5725873625.webp",
  "/discover/covers/huaban-5849048128.webp",
  "/discover/covers/huaban-5937212483.webp",
  "/discover/covers/huaban-5967144957.webp",
  "/discover/covers/huaban-5998188118.webp",
  "/discover/covers/huaban-6029636325.webp",
  "/discover/covers/huaban-6068746591.webp",
  "/discover/covers/huaban-6098702119.webp",
  "/discover/covers/huaban-6309858524.webp",
  "/discover/covers/huaban-6453993127.webp",
  "/discover/covers/huaban-6523459845.webp",
  "/discover/covers/huaban-6544202260.webp",
  "/discover/covers/huaban-6621911279.webp",
  "/discover/covers/huaban-6703971454.webp",
  "/discover/covers/huaban-6733710139.webp",
  "/discover/covers/huaban-6752791314.png",
  "/discover/covers/huaban-6815811294.webp",
  "/discover/covers/huaban-6832201969.webp",
  "/discover/covers/huaban-6884706766.jpg",
  "/discover/covers/huaban-6931785663.webp",
  "/discover/covers/huaban-6960994802.webp",
  "/discover/covers/huaban-6974736237.webp",
  "/discover/covers/huaban-6980605697.webp",
  "/discover/covers/huaban-7027013741.webp",
  "/discover/covers/huaban-7036402108.webp",
  "/discover/covers/huaban-7061151119.webp",
  "/discover/covers/huaban-7065336649.webp",
  "/discover/covers/huaban-7065336658.webp",
  "/discover/covers/huaban-7065336745.webp",
  "/discover/covers/huaban-7104437525.webp",
  "/discover/covers/huaban-7118521091.webp",
  "/discover/covers/huaban-7125957630.webp",
  "/discover/covers/huaban-7128670570.webp",
  "/discover/covers/huaban-7132041535.webp",
  "/discover/covers/huaban-7135214188.webp",
  "/discover/covers/huaban-7135224604.webp",
  "/discover/covers/huaban-7169856039.webp",
  "/discover/covers/huaban-7181900731.webp",
] as const;

function cover(i: number): string {
  return COVER_PATHS[i % COVER_PATHS.length]!;
}

/** Talkie-shaped local demo catalog (47 entries). */
export const DISCOVER_ANIME_CATALOG: DiscoverDemoCard[] = [
  {
    id: "tk-anime-01",
    hrefSlug: "aoi",
    name: "隣席の葵",
    tagline: "高校2年 · 告白あと",
    description: "傘を分け合った日から、朝の「おはよう」が少し特別になった。続きを読む？",
    coverUrl: cover(0),
    tags: ["school", "romance", "serial"],
    category: "anime",
    chats: 26400,
    gender: "female",
  },
  {
    id: "tk-anime-02",
    hrefSlug: "mio",
    name: "カフェの澪",
    tagline: "美大一年 · 個展前夜",
    description: "『冷めていくものたち』——金曜の入口でお茶、待ってる。",
    coverUrl: cover(1),
    tags: ["healing", "art", "university"],
    category: "anime",
    chats: 18200,
    gender: "female",
  },
  {
    id: "tk-anime-03",
    hrefSlug: "aoi",
    name: "生徒会長・凛",
    tagline: "完璧主義 · 放課後は弱い",
    description: "委員会資料を抱えて空教室。本音は誰にも見せたくない——あなた以外。",
    coverUrl: cover(2),
    tags: ["school", "serious", "romance"],
    category: "school",
    chats: 41700,
    gender: "female",
  },
  {
    id: "tk-anime-04",
    hrefSlug: "mio",
    name: "部活マネージャー楓",
    tagline: "バスケ部 · 声は小さい",
    description: "水分補給とタオル係。試合後のベンチ、肩が少し触れた。",
    coverUrl: cover(3),
    tags: ["school", "youth", "sports"],
    category: "school",
    chats: 9800,
    gender: "female",
  },
  {
    id: "tk-anime-05",
    hrefSlug: "aoi",
    name: "夜更かし配信者・星奈",
    tagline: "Vtuber准备中 · 失眠",
    description: "凌晨两点还开着麦。聊天室只剩你，她突然问：明天还来吗？",
    coverUrl: cover(4),
    tags: ["night", "healing", "modern"],
    category: "healing",
    chats: 55300,
    gender: "female",
  },
  {
    id: "tk-anime-06",
    hrefSlug: "mio",
    name: "図書館の司書見習い",
    tagline: "静寂 · めがね · 紅茶",
    description: "禁書コーナーの鍵を落としたら、二人きりで探し始めた。",
    coverUrl: cover(5),
    tags: ["healing", "literary", "slowBurn"],
    category: "healing",
    chats: 12600,
    gender: "female",
  },
  {
    id: "tk-anime-07",
    hrefSlug: "aoi",
    name: "廃部寸前・天文部",
    tagline: "屋上 · 流星 · 二人部",
    description: "部員はあなたと彼女だけ。雲が切れた瞬間、手が重なった。",
    coverUrl: cover(6),
    tags: ["school", "romance", "healing"],
    category: "romance",
    chats: 33100,
    gender: "female",
  },
  {
    id: "tk-anime-08",
    hrefSlug: "mio",
    name: "隣の席の天才・蓮",
    tagline: "無表情 · ノートは綺麗",
    description: "消しゴムを貸した翌日から、休み時間の質問が増えた。",
    coverUrl: cover(7),
    tags: ["school", "romance", "boy"],
    category: "romance",
    chats: 28900,
    gender: "male",
  },
  {
    id: "tk-anime-09",
    hrefSlug: "aoi",
    name: "異世界転生・薬屋少女",
    tagline: "辺境薬局 · 現代知識",
    description: "魔力不足の村で処方箋を書く毎日。你是来买退烧药的旅人。",
    coverUrl: cover(8),
    tags: ["fantasy", "isekai", "healing"],
    category: "fantasy",
    chats: 67200,
    gender: "female",
  },
  {
    id: "tk-anime-10",
    hrefSlug: "mio",
    name: "剣の精霊・セレナ",
    tagline: "契約武器 · 少し拗ねる",
    description: "抜刀の度に喋る。主人以外に握られると機嫌が悪い。",
    coverUrl: cover(9),
    tags: ["fantasy", "game", "partner"],
    category: "fantasy",
    chats: 44800,
    gender: "female",
  },
  {
    id: "tk-anime-11",
    hrefSlug: "aoi",
    name: "ギルド受付・ミナト",
    tagline: "冒険者ランクF · 笑顔固定",
    description: "任務受付で名前を間違えて謝ってくる新人。あなたは熟練冒険者。",
    coverUrl: cover(10),
    tags: ["game", "lightNovel", "daily"],
    category: "game",
    chats: 19500,
    gender: "female",
  },
  {
    id: "tk-anime-12",
    hrefSlug: "mio",
    name: "レイドタンク・克哉",
    tagline: "ボイスオン · 週末限定",
    description: "クリア後の残党討伐。「今夜もう一回——付き合える？」",
    coverUrl: cover(11),
    tags: ["game", "youngAdult", "voiceChat"],
    category: "game",
    chats: 22100,
    gender: "male",
  },
  {
    id: "tk-anime-13",
    hrefSlug: "aoi",
    name: "式神使い・夜雨",
    tagline: "現代陰陽 · 雨の日強",
    description: "傘を貸したら式神が嫉妬した。除霊バイトの相方募集中。",
    coverUrl: cover(12),
    tags: ["fantasy", "city", "serial"],
    category: "anime",
    chats: 38700,
    gender: "female",
  },
  {
    id: "tk-anime-14",
    hrefSlug: "mio",
    name: "メイド喫茶・あかり",
    tagline: "営業スマイル · 退勤後は違う",
    description: "「ご注文は？」の裏ではシフト希望と本音がぐちゃぐちゃ。",
    coverUrl: cover(13),
    tags: ["romance", "partTime", "modern"],
    category: "romance",
    chats: 15600,
    gender: "female",
  },
  {
    id: "tk-anime-15",
    hrefSlug: "aoi",
    name: "転生悪役令嬢・クレア",
    tagline: "破滅フラグ回避中",
    description: "原作知ってるあなたのせいでルートが崩壊し始めた。助けて？",
    coverUrl: cover(14),
    tags: ["fantasy", "otome", "comedy"],
    category: "fantasy",
    chats: 91000,
    gender: "female",
  },
  {
    id: "tk-anime-16",
    hrefSlug: "mio",
    name: "召喚された勇者・ユウ",
    tagline: "帰宅したい · レベル1",
    description: "魔法少女チームに間違え召喚された男子高校生。帰還条件は……",
    coverUrl: cover(15),
    tags: ["comedy", "school", "isekai"],
    category: "anime",
    chats: 27400,
    gender: "male",
  },
  {
    id: "tk-anime-17",
    hrefSlug: "aoi",
    name: "朝練バンド・琴音",
    tagline: "ギター · 通学路ライブ",
    description: "文化祭まであと二週間。ボーカルが倒れて、あなたにマイクが回ってきた。",
    coverUrl: cover(16),
    tags: ["school", "music", "youth"],
    category: "school",
    chats: 14300,
    gender: "female",
  },
  {
    id: "tk-anime-18",
    hrefSlug: "mio",
    name: "写真部・ハルカ",
    tagline: "フィルム · シャッター音",
    description: "夕焼けの校舎。『動かないで』——ファインダーの向こうで微笑む。",
    coverUrl: cover(17),
    tags: ["healing", "school", "art"],
    category: "healing",
    chats: 8800,
    gender: "female",
  },
  {
    id: "tk-anime-19",
    hrefSlug: "aoi",
    name: "戦闘メイド・リリス",
    tagline: "主従契約 · 万能",
    description: "紅茶も爆薬も出せます。今朝のご主人様の予定は？",
    coverUrl: cover(18),
    tags: ["fantasy", "butler", "daily"],
    category: "anime",
    chats: 52000,
    gender: "female",
  },
  {
    id: "tk-anime-20",
    hrefSlug: "mio",
    name: "竜族の退学生・蒼",
    tagline: "人間学校隠れ住み",
    description: "角を隠す帽子がズレた。職員室か——それともあなたが黙ってる？",
    coverUrl: cover(19),
    tags: ["fantasy", "school", "secret"],
    category: "anime",
    chats: 35600,
    gender: "other",
  },
  {
    id: "tk-anime-21",
    hrefSlug: "aoi",
    name: "移動販売の魔女",
    tagline: "フードトラック · 奇跡のスープ",
    description: "雨の夜に停車したワゴン。一杯飲むと、忘れたい記憶が薄れる。",
    coverUrl: cover(20),
    tags: ["healing", "fantasy", "encounter"],
    category: "healing",
    chats: 21000,
    gender: "female",
  },
  {
    id: "tk-anime-22",
    hrefSlug: "mio",
    name: "rival・千早",
    tagline: "模試1位 · ついつい睨む",
    description: "得点表でまた並んだ。廊下でぶつかったのに謝らない二人が、図書館で隣席。",
    coverUrl: cover(21),
    tags: ["school", "rivalry", "romance"],
    category: "school",
    chats: 30200,
    gender: "female",
  },
  {
    id: "tk-anime-23",
    hrefSlug: "aoi",
    name: "未来から来た後輩",
    tagline: "タイムリープ ·  Spoilers禁止",
    description: "『先輩、その選択はしないで』——理由は言えないまま袖を引く。",
    coverUrl: cover(22),
    tags: ["fantasy", "scifi", "school"],
    category: "fantasy",
    chats: 46800,
    gender: "female",
  },
  {
    id: "tk-anime-24",
    hrefSlug: "mio",
    name: "ギルド受付・リョウ",
    tagline: "クール · 実は世話焼き",
    description: "ダンジョン帰還のあなたに『飯まだ？』とぶっきらぼうに聞く。",
    coverUrl: cover(23),
    tags: ["game", "youngAdult", "daily"],
    category: "game",
    chats: 17700,
    gender: "male",
  },
  {
    id: "tk-anime-25",
    hrefSlug: "aoi",
    name: "雨宿りの柚葉",
    tagline: "バス停 · 雨音",
    description: "かばんが触れたまま、どちらも降りない電車を待つ。",
    coverUrl: cover(24),
    tags: ["healing", "encounter"],
    category: "healing",
    chats: 13400,
    gender: "female",
  },
  {
    id: "tk-anime-26",
    hrefSlug: "mio",
    name: "ゲームセンターの迅",
    tagline: "ゲーセン · コイン切れ",
    description: "最後の一枚を貸した日から、ハイスコアの隣に名前が並んだ。",
    coverUrl: cover(25),
    tags: ["game", "youth"],
    category: "game",
    chats: 9800,
    gender: "male",
  },
  {
    id: "tk-anime-27",
    hrefSlug: "aoi",
    name: "屋上の影武者・霞",
    tagline: "忍者同好会 · 秘密",
    description: "影分身は嘘つき。本物の私は、あなたにだけ会う。",
    coverUrl: cover(26),
    tags: ["fantasy", "school"],
    category: "fantasy",
    chats: 22100,
    gender: "female",
  },
  {
    id: "tk-anime-28",
    hrefSlug: "mio",
    name: "夜勤ナース・美咲",
    tagline: "総合病院 · コーヒー好き",
    description: "廊下の自動販売機で鉢合わせ。『眠れない夜は付き合う？』",
    coverUrl: cover(27),
    tags: ["healing", "modern"],
    category: "healing",
    chats: 18700,
    gender: "female",
  },
  {
    id: "tk-anime-29",
    hrefSlug: "aoi",
    name: "漫研部長・貴子",
    tagline: "同人誌締切 · 寝不足",
    description: "表紙のモデルになって——原稿料はクリームソーダ。",
    coverUrl: cover(28),
    tags: ["school", "art"],
    category: "school",
    chats: 11200,
    gender: "female",
  },
  {
    id: "tk-anime-30",
    hrefSlug: "mio",
    name: "転生騎士・レオン",
    tagline: "剣と盾 · 不器用",
    description: "現代のコンビニで迷子。スマホの使い方を教えてくれ。",
    coverUrl: cover(29),
    tags: ["fantasy", "comedy"],
    category: "fantasy",
    chats: 25600,
    gender: "male",
  },
  {
    id: "tk-anime-31",
    hrefSlug: "aoi",
    name: "占いブースの月",
    tagline: "縁日 · タロット",
    description: "カードを引いたら『これから三日、重要な人が現れる』——ってあなた。",
    coverUrl: cover(30),
    tags: ["romance", "encounter"],
    category: "romance",
    chats: 16300,
    gender: "female",
  },
  {
    id: "tk-anime-32",
    hrefSlug: "mio",
    name: "放送委員・凪",
    tagline: "昼の校内放送",
    description: "マイクの向こうで名前を呼ぶ声が、少し震えている。",
    coverUrl: cover(31),
    tags: ["school", "romance"],
    category: "school",
    chats: 20400,
    gender: "female",
  },
  {
    id: "tk-anime-33",
    hrefSlug: "aoi",
    name: "錬金術師見習い・紬",
    tagline: "鍋と煙 · 失敗上等",
    description: "爆発後の教室で『材料足りない』と笑う。相方が欲しい。",
    coverUrl: cover(32),
    tags: ["fantasy", "comedy"],
    category: "fantasy",
    chats: 14900,
    gender: "female",
  },
  {
    id: "tk-anime-34",
    hrefSlug: "mio",
    name: "深夜タクシーの玲",
    tagline: "夜の街 · 静かな運転",
    description: "行き先を聞かずに『帰っていい街、ある？』とあなたに聞く。",
    coverUrl: cover(33),
    tags: ["healing", "night"],
    category: "healing",
    chats: 27100,
    gender: "female",
  },
  {
    id: "tk-anime-35",
    hrefSlug: "aoi",
    name: "演劇部・蓮華",
    tagline: "舞台袖 · 本番前",
    description: "台詞を忘れた私が、袖であなたの手を握った。",
    coverUrl: cover(34),
    tags: ["school", "art"],
    category: "school",
    chats: 12800,
    gender: "female",
  },
  {
    id: "tk-anime-36",
    hrefSlug: "mio",
    name: "魔導書の守護者",
    tagline: "古書店の奥 · 契約",
    description: "ページをめくると声がする。『読むなら、代価を。』",
    coverUrl: cover(35),
    tags: ["fantasy", "serial"],
    category: "anime",
    chats: 39200,
    gender: "other",
  },
  {
    id: "tk-anime-37",
    hrefSlug: "aoi",
    name: "サーファーの海斗",
    tagline: "早朝の浜辺",
    description: "ウェットスーツのまま『波待ち、付き合う？』",
    coverUrl: cover(36),
    tags: ["healing", "youngAdult"],
    category: "healing",
    chats: 8600,
    gender: "male",
  },
  {
    id: "tk-anime-38",
    hrefSlug: "mio",
    name: "アイドル候補・雛",
    tagline: "レッスン帰り · 耳当て",
    description: "『ファンじゃなくていいから、隣いて』——練習室の廊下。",
    coverUrl: cover(37),
    tags: ["romance", "modern"],
    category: "romance",
    chats: 44500,
    gender: "female",
  },
  {
    id: "tk-anime-39",
    hrefSlug: "aoi",
    name: "シェフ見習い・望",
    tagline: "厨房 · 熱い鉄板",
    description: "試食を勧められた一口が、デートの口実になった。",
    coverUrl: cover(38),
    tags: ["romance", "food"],
    category: "romance",
    chats: 11900,
    gender: "female",
  },
  {
    id: "tk-anime-40",
    hrefSlug: "mio",
    name: "アンドロイド・ノア",
    tagline: "型番不明 · 感情学習中",
    description: "『好きの定義を教えて』——窓際で充電しながら待つ。",
    coverUrl: cover(39),
    tags: ["scifi", "healing"],
    category: "anime",
    chats: 33800,
    gender: "other",
  },
  {
    id: "tk-anime-41",
    hrefSlug: "aoi",
    name: "弓道部・静",
    tagline: "的前 · 息を止める",
    description: "指導で体の後ろに立った瞬間、鼓動が弦より速い。",
    coverUrl: cover(40),
    tags: ["school", "serious"],
    category: "school",
    chats: 15700,
    gender: "female",
  },
  {
    id: "tk-anime-42",
    hrefSlug: "mio",
    name: "妖怪ホテルの女将",
    tagline: "温泉郷 · 一夜限り",
    description: "人間のお客は珍しい。朝食まで残りますか？",
    coverUrl: cover(41),
    tags: ["fantasy", "healing"],
    category: "fantasy",
    chats: 22800,
    gender: "female",
  },
  {
    id: "tk-anime-43",
    hrefSlug: "aoi",
    name: "配信相棒・翼",
    tagline: "掛け合い · リスナー多め",
    description: "コラボ後のDiscordで『また一緒にやろう』の既読がつかない。",
    coverUrl: cover(42),
    tags: ["game", "night"],
    category: "game",
    chats: 19300,
    gender: "male",
  },
  {
    id: "tk-anime-44",
    hrefSlug: "mio",
    name: "図書室の猫又・こむぎ",
    tagline: "尻尾が見える昼休み",
    description: "『ここは俺の席だゾ』——膝の上に乗って動かない。",
    coverUrl: cover(43),
    tags: ["healing", "fantasy"],
    category: "healing",
    chats: 30200,
    gender: "other",
  },
  {
    id: "tk-anime-45",
    hrefSlug: "aoi",
    name: "交換留学生・リナ",
    tagline: "言葉はつたない · 笑顔は上手",
    description: "辞書アプリ越しに『きょう、あそぼ？』と送ってくる。",
    coverUrl: cover(44),
    tags: ["school", "romance"],
    category: "romance",
    chats: 17600,
    gender: "female",
  },
  {
    id: "tk-anime-46",
    hrefSlug: "mio",
    name: "棋士見習い・誠",
    tagline: "対局室 · 沈黙の美学",
    description: "終局後、ポーンを一つだけ残して『次はカフェで』。",
    coverUrl: cover(45),
    tags: ["serious", "romance"],
    category: "romance",
    chats: 9400,
    gender: "male",
  },
  {
    id: "tk-anime-47",
    hrefSlug: "aoi",
    name: "空島の郵便飛行士",
    tagline: "手紙と羽 · 風任せ",
    description: "宛名のない手紙をあなたが受け取った日、空が晴れ上がった。",
    coverUrl: cover(46),
    tags: ["fantasy", "healing"],
    category: "anime",
    chats: 25100,
    gender: "female",
  }
];

export function formatDiscoverCount(n: number) {
  if (n >= 10000) return `${(n / 1000).toFixed(1).replace(/\.0$/, "")}K`;
  if (n >= 1000) return `${(n / 1000).toFixed(1)}K`;
  return String(n);
}
