// 由 scripts/icons/sync.mjs 生成，请勿手改。新增图标后运行：npm run icons:sync
// 图标字体只下载这里列出的图标。

export const ICON_NAMES = [
  "add",
  "add_photo_alternate",
  "alarm",
  "animation",
  "arrow_back",
  "arrow_forward",
  "attach_file",
  "auto_awesome",
  "badge",
  "bolt",
  "brush",
  "call",
  "call_end",
  "celebration",
  "chat",
  "chat_bubble",
  "check",
  "check_circle",
  "chevron_left",
  "chevron_right",
  "close",
  "content_copy",
  "dark_mode",
  "diamond",
  "dynamic_feed",
  "edit",
  "expand_more",
  "face",
  "favorite",
  "forum",
  "gavel",
  "grid_view",
  "help",
  "home",
  "hourglass_top",
  "how_to_reg",
  "image",
  "info",
  "inventory_2",
  "ios_share",
  "key",
  "light_mode",
  "lock",
  "lock_open",
  "mail",
  "mark_email_read",
  "menu",
  "mic",
  "mic_off",
  "model_training",
  "more_horiz",
  "notifications",
  "open_in_new",
  "palette",
  "payments",
  "person",
  "photo_camera",
  "play_arrow",
  "post",
  "privacy_tip",
  "psychology",
  "public",
  "redeem",
  "school",
  "search",
  "search_off",
  "send",
  "settings",
  "star",
  "storefront",
  "style",
  "sync",
  "toll",
  "train",
  "upload",
  "verified",
  "visibility",
  "visibility_off",
  "volume_up",
  "warning",
  "wb_twilight"
] as const;

/**
 * 只含上面这些图标的 Material Symbols Rounded。
 * FILL 轴开放 0..1，MIcon 的 filled 才会生效；display=block 让字体到达前不显示图标名文字。
 */
export const ICON_FONT_URL =
  "https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0..1,0" +
  `&icon_names=${ICON_NAMES.join(",")}&display=block`;
